### ISSUE TITLE
configure-project assumes namespace name == repository name

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#39]
While this is the common case we, the data team, already have two examples of a project, let's name it A, that deploys containers in a namespace B. Would be nice if the default was kept the same, but a command line flag (_e.g._ `--namespace`) allowed to change that default.

I suggest namespace since the goal of the CircleCI project is to configure the CI of a repository. Hence we assume repository is deployed in a namespace that has the same name as the repository, but can be overriden with a different namespace name. I am not sure I fully understand, though, how the `kubernetes-namespace`, `circleci` and `github` repository are articulated here, so my suggestion may not be the best one.

In a general fashion, would be nice if you could try to take into account not just the basic obvious case when designing a tool. Especially given that the "manual" way to get the credentials to add to a CircleCI project is no longer documented. Hence we need to reverse engineer the scripts to:

1. understand they don't fit our use case;
2. how to learn again the "manual" way of doing things;

Or alternatively, to the least, please do keep the documentation for the manual way around.

**Comment by galdorjt** [comment]
> In a general fashion, would be nice if you could try to take into account not just the basic obvious case when designing a tool.

Yes, a lot of things would be nice. But everything we do is associated with a time budget and multiple other constraints, so we often have to implement the general case which works for the vast majority of people here, then wait for specific demands to add options. As always, you can just ask and we'll do our best to help.

In general, for services, we want the same name for the repository and the namespace, simply because it makes life easier. I'm fine with having the possibility to select a different namespace, but it will probably require some work at multiple places depending on how far you want it to go.

Regarding a `--namespace` command line option, which tool are your referring to ?
