### ISSUE TITLE
Latest change to the docker orb seems to break some of our workflows

### ISSUE THREAD

**Issue by cansjt** [jobteaser/circleci#43]
Since [systematic push of the `latest` tag was added](https://github.com/jobteaser/circleci/commit/6beb620a49ef7b63bcf437ccf726ed9ce17ba455#diff-cbea1cf9e4d521a2749529f57bb294f2) to the `docker` orb, from time to time pushing the tag latest fails on some of our projects.

Example:
https://app.circleci.com/pipelines/github/jobteaser/data-tracking-plan/1678/workflows/19960aa8-46c9-4b86-b569-9ea890281e2c/jobs/3818

From our stand point we don't care about that tag as we always use explicit tags in our workflow, which makes sense to have truly immutable infrastructure (every revision should be explicit, set in stone, `latest` is implicit and changes over time).

**Comment by gearnode** [comment]
You have to use the complete job or at least the command provide by the orbs to not have this kind of issue. In the other hand your workflow the latest tag of the circleci orb, if you want be sure nothing change on your circleci pipeline because your have build custom thing around the CircleCI orbs you can use stable versioning and bump when you want to a new version.

On the latest tag we never use it to deploy production or staging release, the latest is for local setup and help people to easily debug latest docker image.

**Comment by cansjt** [comment]
'Cause @gearnode you put it back on the table, while at the Ballu the other day :wink: , actually there is a better way to do this, one that would not have broken any build:
- Do not add the `latest` tag in the build step.
- When you are asked to push the `latest` tag in the push step, do add the tag on the image and immediately push it; 

I think it simplifies the the number of steps required. Of course I am pretty that you will reject the PR anyways, has it changes the orb "API", but just for the sake of the argument... I think I win ! :1st_place_medal: :checkered_flag: :upside_down_face: 

(by the way, maybe I missed something, but why do you use two pushes in the job definition ? once for the "normal" tag, once for the latest with the condition, given that there is a condition (`if`) in the shell script of push_image step ?)

Ok time to go on vacation :palm_tree: :sun_with_face:
